<a href="https://colab.research.google.com/github/sipocz/Colab/blob/main/SL_Numpy_teszt_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [38]:
import numpy as np # the prefix is "np" by convention


In [39]:
m1=np.array([[1,2,3],[4,5,6],[7,2,9]])
m1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 2, 9]])

In [40]:
m2=np.array([[1.0,2.0,3.0],[4.0,5.0,6.0],[7.0,2.0,9.0]])
m2

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 2., 9.]])

In [41]:
np.matmul(m1,m2)

array([[ 30.,  18.,  42.],
       [ 66.,  45.,  96.],
       [ 78.,  42., 114.]])

In [44]:
print(m1)
mi=np.invert(m1)
print(mi)

[[1 2 3]
 [4 5 6]
 [7 2 9]]
[[ -2  -3  -4]
 [ -5  -6  -7]
 [ -8  -3 -10]]


In [43]:
np.matmul(m1,mi)

array([[ -36,  -24,  -48],
       [ -81,  -60, -111],
       [ -96,  -60, -132]])